### ISSUE TITLE
Trying to download a .torrent

### ISSUE THREAD

**Issue by emnoze** [pitzzae/yggtorrent#1]
Hi,
I m using your lib for making a " download center ".
So i got the id but i don't understand how your 

> client.get_torrent(function(buf, error) {
    // `buf` is a Buffer or null, `error` is string or null
    if (error)
      console.log(error);
    else
    {
      const parsed = require('parse-torrent')(buf);
      console.log(parsed);
    }
  }, id);

>
is working ?

**Comment by pitzzae** [comment]
Hi,

I have test it yet, its working.

The first arg of client.get_torrent its callback of the method, the second arg its the id of the torrent you want to download

The callback method have 2 args, first its a buffer contain base64 string of the torrent file, the second arg its error status

If id of the torrent is right:
buf = buffer of base64 string,
error = null

If id of the torrent is wrong:
buf = null
error = string msg error

You need to use
client.set_credential('your-username', 'your-password');
to download a torrent

If your credential is wrong you can see the result on error arg when you download a torrent
